### ISSUE TITLE
完善中文API

### ISSUE THREAD

**Issue by nobodxbodon** [icela/FriceEngine-DSL#1]
源自: https://github.com/icela/FriceEngine/issues/40#issuecomment-351620329

恐怕第一步是搭建开发环境. 如有弱问题还请包涵. 
请问可以提PR修改已有的[中文接口](https://github.com/icela/FriceEngine-DSL/blob/master/LanguageE/src/Chinese.kt)吗?

**Comment by ice1000** [comment]
是的，非常欢迎。

**Comment by ice1000** [comment]
搭建环境： https://icela.github.io/#with-intellij-idea
然后建议使用中文重写 https://github.com/icela/FriceEngine-DSL/blob/master/src/org/frice/dsl/Base.kt
而不是基于现在那个改。现在那个我都看不下去了，感觉很挫。

**Comment by nobodxbodon** [comment]
有没有考虑把jar包发布到maven库? [之前](https://zhuanlan.zhihu.com/p/28024364)试过还算方便.

**Comment by ice1000** [comment]
因为目前JitPack满足需求了就没弄maven中心了，感觉审核挺麻烦的，而且我是那种写代码很快的人，一两天就一个新版本。。。
如果可以的话，可以麻烦你吗。
主仓库和这个都是。

目前所有已知bug已全部修复。

**Comment by ice1000** [comment]
感觉如何？上手了吗

**Comment by nobodxbodon** [comment]
刚跑了首页的演示[flappy bird](https://github.com/icela/FriceDemo/blob/master/1.7.6/Demo7.java), 一按向上键就飞不见了啊.
这几天不一定有空. 有些人生大事要决定 lol

**Comment by ice1000** [comment]
你需要调用了最新的 API 的 [flappy bird](https://github.com/icela/FriceDemo/blob/master/1.7.9/Demo7.java)

**Comment by nobodxbodon** [comment]
好像AccelerateMove的参数有些不妥. 现在刚打开就跳出"game over"(还没图形显示)
请问用DSL写的flappy bird例程有吗? 没有也OK, 现在的[例程](https://github.com/icela/FriceEngine-DSL/blob/master/LanguageE/test/ChineseDemo.kt)已经比hello world复杂多了.

**Comment by ice1000** [comment]
那可能是我写的不大好吧。没显示是因为创建窗口前就掉下去了。。。
你试试把覆盖onInit改成覆盖onLastInit。

用DSL的话，我今下午有空我就写一个。

**Comment by ice1000** [comment]
你在 pull request 里面说的那个编译错误我已经修复啦。

**Comment by nobodxbodon** [comment]
@ice1000 收到, 多谢! 一个问题: 为何oval返回shape, 但rectangle不返回呢?

**Comment by ice1000** [comment]
现在oval也不返回了。

可能写的时候脑抽了。这个东西的返回值一般也用不上。没啥意义。

**Comment by ice1000** [comment]
还有其他问题吗？我觉得可以 close issue 了。
等 1.7.12 出来，我就再加点 DSL API 。。

比如 `EventManager` ，我感觉不用白不用

**Comment by nobodxbodon** [comment]
有个问题, 测试中的几个rectangle意义是否不同?
```kotlin
		whenUpdate {
			if (800.elapsed()) {
				rectangle {  <--------------
					x = elapsed / 10.0
					y = elapsed / 10.0
					color = PINK
				}
			}
		}

		rectangle {<--------------
			name("rectangle")<--------------
			x = 100.0
			y = 100.0
			width = 100.0
		}
		oval {
			x = 0.0
			y = 85.0
			accelerate {
				x = 10.0
//				y = 10.0
			}
			whenColliding("rectangle") {<--------------
				stop()
				x -= 5
				accelerate(-2, 10)
			}
		}
```

**Comment by ice1000** [comment]
name 是给一个对象起名字，然后whenColliding的时候传入名字。

**Comment by ice1000** [comment]
而 rectangle 本身是一个函数。

字符串那个 rectangle 你可以试试改成其他的。都没有问题

**Comment by ice1000** [comment]
```kotlin
	rectangle {<--------------
			name("233")<--------------
			x = 100.0
			y = 100.0
			width = 100.0
		}
		oval {
			x = 0.0
			y = 85.0
			accelerate {
				x = 10.0
//				y = 10.0
			}
			whenColliding("233") {<--------------
				stop()
				x -= 5
				accelerate(-2, 10)
			}
		}
```

这个也行。

**Comment by nobodxbodon** [comment]
@ice1000 多谢. `whenColliding`的判定条件是...? 好像测试时没有反弹效果啊

**Comment by ice1000** [comment]
碰撞。

**Comment by ice1000** [comment]
碰撞之后不会反弹，我没做物理引擎。碰撞的时候会触发那个代码块（就是whenColiiding的），然后你可以在里面手动添加反弹效果（就是动画）

**Comment by nobodxbodon** [comment]
? 难道这个意思不是反弹?
```kotlin
			whenColliding("233") {
				stop()
				x -= 5
				accelerate(-2, 10)
			}
```

**Comment by ice1000** [comment]
collide 是碰撞，不是反弹。。

**Comment by ice1000** [comment]
我发现了。这是重构的时候遗留的bug。
我开了 #5 ，现在已经修复。

**Comment by ice1000** [comment]
遇到其他问题可以单开 issue @nobodxbodon

**Comment by nobodxbodon** [comment]
OK. 本来是想用这个issue track接口中文化的进度. 不过看来会比较久(而且随着DSL API的添加会是个持续的过程). 也许用Project更合适? 或者我在org里track也行.

**Comment by ice1000** [comment]
有milestone，配合release。
引擎主仓库就是这么搞的，你可以去看

**Comment by ice1000** [comment]
引擎主仓库指 icela/FriceEngine

**Comment by ice1000** [comment]
那就这么决定了
