### ISSUE TITLE
测试中使用相对文件路径

### ISSUE THREAD

**Issue by nobodxbodon** [icela/FriceEngine-DSL#3]
可否把[png文件](https://github.com/icela/FriceEngine-DSL/blob/master/test/Test.kt#L56)提交?

**Comment by ice1000** [comment]
你可以把 `file` 改成 `url` ，然后给个链接，就可以显示在线图片资源了（就不需要读取本地的了）。

```kotlin
// 通过本地文件创建
// file("C://frice.png")
// 也可以使用url创建基于网络的图片
url("https://avatars3.githubusercontent.com/u/16398479")
```

这个是我的 GitHub 头像。

我不愿意在仓库里面放置测试用的资源文件。。。所以不会提交的。

**Comment by nobodxbodon** [comment]
ok. 之前不知道url也可以. 不过测试用的资源文件还是蛮多的吧

**Comment by ice1000** [comment]
没，就图片啥的
