### ISSUE TITLE
测试用例占用cpu问题

### ISSUE THREAD

**Issue by nobodxbodon** [icela/FriceEngine-DSL#4]
好像会用到100%, 不知是否正常?

**Comment by ice1000** [comment]
不清楚。我这只有3个线程（Swing自己一个，我创建的一个，和主线程），有可能你看的是编译的那个程序？

**Comment by nobodxbodon** [comment]
![screen shot 2017-12-20 at 10 53 07 am](https://user-images.githubusercontent.com/392497/34223400-1385fd62-e574-11e7-8f7b-e04674c8cb9e.png)
应该是 swing吧?

**Comment by nobodxbodon** [comment]
试了一下 `game{}`删空也是100-200%, 这和fps太高有关吗?

**Comment by ice1000** [comment]
不清楚。我是开了个线程死循环不停地刷新的。

这很正常。

```c
int i;
for (i = 0; i < 1000000; ++i);
```

也可以占用100%的CPU。。

**Comment by nobodxbodon** [comment]
请问有什么特别原因不用`javafx.animation`吗? 刚试了[这个](https://github.com/tutsplus/Introduction-to-JavaFX-for-Game-Development/blob/master/Example3.java)示例, 只要10%cpu

**Comment by ice1000** [comment]
JavaFX 是最近才加上的，主体绘制逻辑早就写好了。你说的那个连自己控制fps都不行（起码我没看到），更何况我用的最多的其实是 Swing （在 Linux 下反而感觉 Swing 的字体要好看点， JavaFX 默认的字体太小了。。

**Comment by ice1000** [comment]
JavaFX 还会一直维护下去就是了，我两套平台的逻辑是共用的，除了平台相关的绘制代码外全部都是复用了的。要是特化其中一个，就违法DRY原则了。
